### ISSUE TITLE
Custom transcript summarization

### ISSUE THREAD

**Issue by vishnu-chalil** [gcunhase/AMICorpusXML#3]
How can I use this code and create summary for a new raw transcript containing multiple user dialogues?Is there any major changes needed.

**Comment by gcunhase** [comment]
This code is not to generate summaries given some transcript, but rather to re-format the AMI Corpus dataset from `.xml` to `.story` files.

Is that what you were asking?

**Comment by gcunhase** [comment]
Closing due to lack of response.
